name: CI decovid-19-client

on:
  push:
    branches: [ 'main' ]
    tags:
      - '*'
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: npm install

      - name: Setup
        run: npm ci

      - name: Linters and Prettier
        run: npm run all-lints

      - name: Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: npm test
